### ISSUE TITLE
Non-platform agnostic module causes issues with bundlers

### ISSUE THREAD

**Issue by Desplandis** [connormanning/copc.js#6]
Hi!
First and foremost, thanks for your library, it is nicely written and very readable!

We will be using it as the parsing library for `copc` (and maybe `entwine`) pointclouds on [`itowns`](https://github.com/iTowns/itowns), a library for visualizing different types of 2D/3D geospatial data in a **browser** environment. As such, we would like our library to work out-of-the box with no additional configuration on users' bundlers.

However, `copc.js` lazy-load the `fs` **node** module which is not platform agnostic. This causes bundling issues with at least `webpack` and `vite` (the ones I currently tested).

Is this a wanted behavior on your side?

**Comment by connormanning** [comment]
This is intentional, but maybe worth reconsidering.  With `fs` being lazily-loaded, you can bundle an application/library for the web, and then *also* be able to use that library in Electron (for example) to get native filesystem access in a hybrid desktop/web application.  And of course the code paths using the `fs` module will not be reached in a pure web environment.

In the rollup configuration for downstream applications, I set `fs` to be a global, but I think most bundlers have an option to set an import as `null`, for example the `null-loader` in webpack.  Would this be an option for you?  If you set `fs` to be a null import, then your downstream users would have no references to `fs` in your bundle.

**Comment by connormanning** [comment]
Here is an example of this in webpack: https://github.com/connormanning/copc-umd/blob/78249ffb2a2ddf3d8d63ef9eb9f9ddacbdc40228/webpack.config.js#L10-L14

I used this to generate a browser-only UMD bundle.  You could add this to your own config, or create a similar re-exporting package with an appropriate bundle for your use-case.  I'm not fully clear (from the referenced ticket) why you would need a fork to accomplish this: so feel free to open a new ticket with specific steps to demonstrate your issue if you'd like me to take a look at something specific.

**Comment by Desplandis** [comment]
The problem is that as a library we cannot expect that our users add additional configurations for each of our dependency. Unfortunately bundlers (especially `webpack`) are not smart enough to prune lazy-loaded `node.js` modules...

I will push a PR to add a hint for those bundlers to ignore the `fs` module. It should fix this issue for at least webpack and vite. =)
