### ISSUE TITLE
Can this library be used to read plain LAS files ?

### ISSUE THREAD

**Issue by sguimmara** [connormanning/copc.js#9]
I need to be able to read regular LAS/LAZ files, and I was wondering if the library has some kind of "fallback" when the file is not a COPC (i.e expose a single root node for the whole file) ?

**Comment by connormanning** [comment]
There is no "fallback" the way you describe, such that you could treat a LAS/LAZ file as COPC.  However all of the building blocks you need to work with non-COPC LAS files should already exist so that you can handle them appropriately.  For example, parsing the header, checking for the COPC VLR (note that it is specified that it must be the first VLR, so you don't have to walk them all), and handling the data as LAS/LAZ if necessary.

For example, you might look at the [`Las.PointData`](https://github.com/connormanning/copc.js/blob/master/src/las/point-data.test.ts) tests to see how that API is used.  These building blocks are the ones used by the `Copc` API for its handling of the LAS aspect of the data, and you can use them yourself with `import { Las } from 'copc'`.

**Comment by sguimmara** [comment]
Yes, that's what I ended up doing, trying to refactor as much commonality as possible.

Thanks, closing this.
